### ISSUE TITLE
taxonomic names messed up

### ISSUE THREAD

**Issue by myrmoteras** [sibils/community#2]
### Service

Biodiversity PMC

### Contact Details

agosti@amnh.org, 

### What happened?

issue with document 10.3391/ai.2023.18.2.106252 from collection pmc  https://sibils.text-analytics.ch/search/?query=%20Hemigrapsus%20sanguineus%20spilmont&tab=pmc#results-section

![image](https://github.com/sibils/community/assets/4609956/f9104b11-715e-4b20-b88a-4f88ddfd621e)

in the original [XML](https://aquaticinvasions.arphahub.com/article/106252/download/xml/)

![image](https://github.com/sibils/community/assets/4609956/4a78ac32-227f-46b6-8d9c-e8b7a95e790b)

in [html](https://aquaticinvasions.arphahub.com/article/106252/) 
![image](https://github.com/sibils/community/assets/4609956/59e20a78-da5c-4b62-8f5c-aad7091ec1b2)

@daniel-mietchen

### What did you expect to happen?

soll `H. sanguineus`,  `M. edulis`, `P. littoralis` sein 

### What browsers are you seeing the problem on?

Chrome

### Service url

https://sibils.text-analytics.ch/search/?query=%20Hemigrapsus%20sanguineus%20spilmont

**Comment by emilie19** [comment]
ping @jgobeill

**Comment by emilie19** [comment]
![Capture d’écran 2024-02-05 à 10 34 25](https://github.com/sibils/community/assets/20300719/b2863132-bf1e-4bf2-a5e2-6ef95ba508a1)

The issue is fixed
